#!/bin/sh

set -e
set -u

version="${1}"

platform=$(uname)

NJOBS="${NJOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || true)}"
NJOBS="${NJOBS:-1}"

echo "parallel job count: ${NJOBS}"

cd "src/node-${version}"

PYTHON="${PYTHON:-python2}"

"${PYTHON}" configure --openssl-no-asm --without-npm --shared --with-intl=small-icu
make BUILDTYPE=Release config.gypi
make BUILDTYPE=Release out/Makefile

export PATH="${PWD}/out/tools/bin:${PATH}"
make -j"${NJOBS}" -C out BUILDTYPE=Release V=0 libv8_monolith
