#!/bin/sh

set -e
set -u

version="${1}"

platform=$(uname)

case "${platform}" in
    SunOS)
        TAR="${TAR:-gtar}"
        ;;
    *)
        TAR="${TAR:-tar}"
        ;;
esac

"${TAR}" -C src -xz -f "src/node-${version}.tar.gz"

cd "src/node-${version}"

patch -p1 < ../../gyp-libv8_monolith.patch
patch -p1 < ../../py2-genv8constants.patch
